apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80  # A porta que o serviço escuta
      targetPort: 8080  # A porta que será encaminhada para as instâncias
  type: LoadBalancer
